### ISSUE TITLE
行列の積を行う関数を作る(C言語)

### ISSUE THREAD

**Issue by POCHI-CUTE** [POCHI-CUTE/Okada-Lab-FPM#4]
行列の積を行う関数をお願いします。

**Comment by MatsuoKoyo-1997** [comment]
C で以下のような関数を作りました。

2次元配列のポインタに行列（2次元配列）A、Bの積ABを代入する関数 multiMatrix
(使用例)
double **X = multiMatrix("Aの行数", "Bの列数", "行列A", "行列B", "Aの列数(=Bの行数)")
Xは後にメモリの解放を行う必要があります。

**Comment by POCHI-CUTE** [comment]
確認しておきます!
